puts "------------------------------------------Starts Seeding-----------------------------"
Game.destroy_all
User.destroy_all

    yoshi = User.create(name: "Yoshi")
    link = User.create(name: "Link")
    mario = User.create(name: "Mario")
    zelda = User.create(name: "Zelda")

    puts"-------------------------------------Users Sedded------------------------------------"

    Game.create(
        game_name: "New Super Lucky's Tale",
        game_description:"Want to read more? See our full Sunset Overdrive review.",
        game_image: "https://d2skuhm0vrry40.cloudfront.net/2021/articles/2021-02-19-14-18/best_game_pass_games_18.jpg/EG11/resize/690x-1/quality/75/format/jpg",
        user_id: yoshi.id
        )
    Game.create(
        game_name: "Microsoft Flight Simulator",
        game_description: "Game Pass Platforms: Xbox One, Xbox Series X|S, PC",
        game_image:  "https://d2skuhm0vrry40.cloudfront.net/2021/articles/2021-02-19-14-18/best_game_pass_games_16.jpg/EG11/resize/690x-1/quality/75/format/jpg",
        user_id: mario.id
        )
    Game.create(game_name: "Moonlighter", game_description: "So many jokes - and many of them hit their marks. But also so much cheer and colour and zip. Before Insomniac mastered its open-world superhero schtick with Spider-Man for the PS4, the Xbox got this, a wonderfully zany shooter that delights in the pleasures of movement as you zip around, bounce across the rooftops and unlock deliriously odd weaponry. Deep down this is a big budget version of The Floor is Lava. It's a real treat." , game_image: "https://d2skuhm0vrry40.cloudfront.net/2021/articles/2021-02-19-14-18/best_game_pass_games_17.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: link.id)
    Game.create(game_name: "Tom Clancy's Rainbow Six Siege", game_description: "Want to read more? See our full Lonely Mountains: Downhill review.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_15.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: zelda.id)
    Game.create(game_name: "Hollow Knight", game_description: "The soundtrack really sells this: windy solitude with the twittering of birds, the creaking of branches, the scrape of gravel under your tyres. Lonely Mountains may be a game about bombing around in a bike, but it's also about the world you're bombing through - nature at its empiest and most moving, all delivered with low-poly visuals and a devious wit when it comes to track design. Beat times and unlock bike parts if you fancy, but the setting is the star here. This is a game to load up just to spend time in its world.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_14.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id:"")
    Game.create(game_name: "Stellaris", game_description: "Game Pass Platforms: Xbox One, Xbox Series X|S, PC, xCloud", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_14.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id:link.id)
    Game.create(game_name: "Sea of Thieves", game_description: "Want to read more? See our full Halo: Master Chief Collection review.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_12.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: mario.id)
    Game.create(game_name: "Wasteland 3", game_description: "The quintessential Game Pass game for obvious reasons, the Master Chief Collection is about as good a deal as it gets. Several of the best shooters ever made, combining some of the best campaigns, the best levels, the best local co-op fun you can casually have and the best high-skillcap online multiplayer maps, too. Beautiful, nostalgic, and genuinely essential playing. It's a boring choice, yes, but a fantastic one. The PC version now includes all six games, too: Combat Evolved Anniversary, 2 Anniversary, 3, ODST, Reach, and 4.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2021/articles/2021-02-19-14-18/best_game_pass_games_11.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: zelda.id)
    Game.create(game_name: "Yakuza 0", game_description: "Game Pass Platforms: Xbox One, Xbox Series X|S, PC, xCloud", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_10.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: yoshi.id)
    Game.create(game_name: "Destiny 2: Beyond Light and Expansions", game_description: "Want to read more? See our full Nuclear Throne review.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2021/articles/2021-02-19-14-33/best_game_pass_games_9.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: mario.id)
    Game.create(game_name: "Forza Horizon 4", game_description: "From the masters of short, sharp arcade action at Vlambeer - the studio that brought us Luftrausers, Super Crate Box and Ridiculous Fishing - comes this action roguelike set in a ravaged mutant wasteland. It's a top-down, run-and-gun shooter that offers amazing variety and tactical breadth in its procedural stages and combinations of characters and weapon loadouts. The retro graphics may look crude but the game is blistering in motion - and it sets an equally blistering pace, with runs lasting a matter of minutes. That makes it one of the most uncompromising games of its kind, but also perversely one of the most accessible, because it's such an easy decision to just hit restart.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2021/articles/2021-02-19-14-17/best_game_pass_games_8.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id:link.id)
    Game.create(game_name: "Star Wars Battlefront 2", game_description: "Game Pass Platforms: Xbox One, Xbox Series X|S, PC", game_image: "https://d2skuhm0vrry40.cloudfront.net/2021/articles/2021-02-19-14-17/best_game_pass_games_7.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id:"")
    Game.create(game_name: "Tetris Effect: Connected", game_description: "Want to read more? See our full What Remains of Edith Finch review.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_6.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: mario.id)
    Game.create(game_name: "Titanfall 2", game_description: "When we are gone our books will still be piled up in the hallways and our clutter will still spill through the house. This is the premise of What Remains of Edith Finch, an inquest by way of exploration. It works because the writing is vivid and the setting is astonishing: a family home that has become progressively more addled with each code-violating extension. Really though, what surprises is how this sad little game about death is so staggeringly filled with life. Stellar.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_5.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id:"")
    Game.create(game_name: "Scourgebringer", game_description: "Game Pass Platforms: Xbox One, Xbox Series X|S, PC, xCloud", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_4.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: yoshi.id)
    Game.create(game_name: "Sunset Overdrive", game_description: "17 Xbox Series X tips and tricks, for the UI and homescreen", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_3.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: yoshi.id)
    Game.create(game_name: "Lonely Mountains: Downhill", game_description: "This list includes games that are available on either Xbox consoles or PC or both (most variations of the subscription cover both!), and many of them are now available on mobile devices and browsers via Xbox Cloud Gaming, too. But for a list of absolutely everything available - just in case you want to rightfully berate us for missing a favourite - you can peruse our full Xbox Game Pass games list.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2021/articles/2021-09-09-12-28/A_hail_of_bullets_in_Nuclear_Throne.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: "")
    Game.create(game_name: "Halo: Master Chief Collection", game_description: "Before we dive in, too, note that you can pick up a single-month starter subscription for just a pound here, or you can top up a subscription if you already have one here.", game_image: "https://d2skuhm0vrry40.cloudfront.net/2020/articles/2020-04-17-11-34/best_game_pass_games_1.jpg/EG11/resize/690x-1/quality/75/format/jpg", user_id: link.id)
    Game.create(game_name: "Nuclear Throne", game_description: "Here, we've picked out the 20 best Game Pass games you can download right now. But don't read this as a canonical list - we're not into that - and instead look at it as 20 games that cover the impressive range of the subscription. Game Pass is about flicking through a library and trying something out you might have skipped, or finding a hidden gem you might have completely missed altogether. There are some big hitters we've left out, but that shouldn't really be a surprise. Everybody knows Gears of War is a Game Pass game and everyone's already bought GTA 5 three times. What are the 20 games you really should play?", game_image: "https://tse4.mm.bing.net/th?id=OIP.H3Hqe5FNPoB3a6ysPtU_QgHaHa&pid=Api&P=0&w=300&h=300", user_id: zelda.id)
    Game.create(game_name: "What Remains of Edith Finch", game_description: "Game Pass is pretty incredible for the user. A monthly subscription grants you access to hundreds of games, many of which are genuinely great." , game_image: "https://gamernetwork.bbvms.com/mediaclip/4099089/pthumbnail/688/388.jpg", user_id: zelda.id)

puts"------------------------------ Done Seeding!----------------------------"
